version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: DBZucchetti
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
