# Imagem base PHP com Apache incluído
FROM php:8.0-apache

# Define o diretório de trabalho
WORKDIR /var/www/html

# Copia o código fonte para o diretório de trabalho
COPY . .

# Expõe a porta 80 para o serviço web
EXPOSE 80
